In [7]:
import numpy as np
scores = np.array([[85, 90, 78],
                   [92, 98, 85],
                   [76, 95, 85],
                   [90, 85, 92],
                   [88, 76, 89]])

# 1. Calculate the mean score of each subject (across all students)
mean_scores = np.mean(scores, axis=0)
print("Mean score of each subject:", mean_scores)

# 2. Find the median score of each student (across all subjects)
median_scores = np.median(scores, axis=1)
print("Median score of each student:", median_scores)

# 3. Extract the scores of the student with the highest total score (sum of all subjects)
total_scores = np.sum(scores, axis=1)
highest_score_index = np.argmax(total_scores)
highest_score_student = scores[highest_score_index]
print("Scores of the student with the highest total score:", highest_score_student)

# 4. Find the minimum and maximum scores in each subject
min_scores = np.min(scores, axis=0)
max_scores = np.max(scores, axis=0)
print("Minimum scores in each subject:", min_scores)
print("Maximum scores in each subject:", max_scores)

# 5. Reshape the array to have shape (3, 5), where each row represents a subject and each column represents a student
reshaped_scores = scores.T  # Transposing will achieve this directly
print("Reshaped array (3, 5):")
print(reshaped_scores)

# 6. Sort the scores of each subject in ascending order
sorted_scores = np.sort(scores, axis=0)
print("Sorted scores of each subject:")
print(sorted_scores)




Mean score of each subject: [86.2 88.8 85.8]
Median score of each student: [85. 92. 85. 90. 88.]
Scores of the student with the highest total score: [92 98 85]
Minimum scores in each subject: [76 76 78]
Maximum scores in each subject: [92 98 92]
Reshaped array (3, 5):
[[85 92 76 90 88]
 [90 98 95 85 76]
 [78 85 85 92 89]]
Sorted scores of each subject:
[[76 76 78]
 [85 85 85]
 [88 90 85]
 [90 95 89]
 [92 98 92]]
